services:
  - type: web
    name: pdf-merger-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300 --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
